name: Download and preprocess 18UTC

on:
  schedule:
    - cron: '0 3 * * *'  # This runs every day at 10:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Cache Python packages
        uses: actions/checkout@v4
        with:
          cache: 'pip'
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt  # Install your dependencies

      - name: Run Jupyter Notebook
        run: |
          source venv/bin/activate
          rm src/*.json
          ipython -c "%run src/singlelevel-Updated.ipynb"
          rm src/atms.grib2*
      - name: Commit and push changes
        run: |
          git config --global user.name "subhrajitjubu"
          git config --global user.email "66462700+subhrajitjubu@users.noreply.github.com"
          git add src/*.json
          git commit -m "Update files created by Jupyter Notebook"
          git push origin main
