name: Download and preprocess 00UTC

on:
  schedule:
    - cron: '0 9 * * *'  # This runs every day at 10:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt  # Install your dependencies

      - name: Pull repo
        run: |
          git config --global user.name "subhrajitjubu"
          git config --global user.email "66462700+subhrajitjubu@users.noreply.github.com"
          git pull origin main

      - name: Run Jupyter Notebook
        run: |
          source venv/bin/activate
          rm src/*.json
          ipython -c "%run src/singlelevel_00.ipynb"
          rm atms.grib2*

      - name: Compress JSON files
        run: |
          tar -czvf json_files.tar.gz src/*.json

      - name: Commit and push compressed files
        run: |
          git config --global user.name "subhrajitjubu"
          git config --global user.email "66462700+subhrajitjubu@users.noreply.github.com"
          git pull origin main
          git add json_files.tar.gz
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update compressed JSON files"
            git push origin main
          else
            echo "No changes to commit."
          fi

      - name: Uncompress JSON files (optional)
        run: |
          tar -xzvf json_files.tar.gz  src/
